config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'recipes#index'
  match 'recipes', :to => 'recipes#index', :via => :get

  get '/ingredients/:id', to: 'ingredients#show', as: 'show_ing'
  get '/ingredients/new/:id', to: 'ingredients#new', as: 'new_ing'



  resource :recipes, only: [:index,:new,:create]
  resource :ingredients, only: [:show,:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :name, presence: true
  validates :description, presence: true

  scope :findall, ->(num) { where("recipe_id = ?", num) }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  validates :name, presence: true , uniqueness: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def show
    @ingredients = Ingredient.findall(params[:id])
    #@ingredients = Ingredient.find(params[:id])
    @ing_name = Recipe.find(params[:id]).name
  end

  def new
    #@recipe_id = Recipe.find(params[:id])
    @ingredient = Ingredient.new
  end

  def create
    #@recipe_id = params[:id]
    @ingredient = Ingredient.new(recipe_params)
    if @ingredient.save
      flash[:notice] = "Ingredient Added Succesfully"
      redirect_to(root_path)
    else
      flash[:notice] = "An error occured Please Try Again"
      render('new')
    end
  end

  def recipe_params
    params.require(:ingredient).permit(:recipe_id,:name,:description)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "Recipe Created Succesfully"
      redirect_to(root_path)
    else
      render('index')
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name,:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/new.html.erb
<h1>New Ingredient Form</h1>

<p>Add Ingredient for <%= Recipe.find(params[:id]).name %> recipe</p>

<%= bootstrap_form_for(@ingredient,:url => ingredients_path) do |f| %>
    <%= f.text_field :recipe_id , :required => true , :readonly => true , :value => params[:id]%>
    <%= f.text_field :name , :required => true%>
    <%= f.text_area :description,:required => true, :rows => 7 %>
    <%= f.submit 'Submit' %>
<% end %>
<br />

<%= render(:partial => 'recipes/button') %>

app/views/ingredients/show.html.erb
<h2>Showing Ingredient/s for : <%= @ing_name %></h2>
<table class = "table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  </thead>
  <tbody>
  <% @ingredients.each do |i| %>
      <tr>
        <td><%= i.name %></td>
        <td><%= i.description %></td>
      </tr>
  <%end%>
  </tbody>
</table>

<br />

<%= render(:partial => 'recipes/button') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Recipes</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
    <% if !flash[:notice].blank? %>
        <div class="alert alert-success">
        <%= flash[:notice]%>
        </div>
    <%end%>
    <%= yield %>
      </div>
      <div class="col-lg-12">
        <p></p>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/recipes/_button.html.erb
<div class="col-lg-4 text-center">
  <%= button_to 'Back to Homepage', root_path , class: 'btn btn-primary btn-lg' , method: :get %>
</div>

app/views/recipes/index.html.erb
<h1>RECIPES HOMEPAGE</h1>

<br />

<table class = "table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Ingredients No</th>
  </tr>
  </thead>

  <tbody>
  <% @recipes.each do |i| %>
  <tr>
    <td><%= i.name %></td>
    <td><%= i.description %></td>
    <td><%= link_to(i.ingredients.size,show_ing_path(i)) %></td>
    <td><%= link_to("Add Ingredient",new_ing_path(i))  %></td>
  </tr>
  <% end %>

  </tbody>

</table>


 <%-# button_to "ADD RECIPE", action: "new" , method: :get -%>

<%= link_to("Add new Recipe",new_recipes_path,:class => "btn btn-success")%>

app/views/recipes/new.html.erb



<h3>FORM FOR NEW RECIPE</h3>


<%= bootstrap_form_for(@recipe,:url => recipes_path) do |f| %>
    <%= f.text_field :name , :required => true%>
    <%= f.text_area :description,:required => true, :rows => 7 %>
    <%= f.submit 'Submit' %>
<% end %>

<br />
<%= render(:partial => 'button') %>